<template>
    <v-footer class="pt-4 pb-10 px-0">
      <div class="row px-xl-0 px-lg-0 px-md-6 px-sm-4 px-4 no-gutters justify-center"><div class="mw-75-v col-lg-9 col-12"><div class="row custom-text-noto no-gutters"><button type="button" class="small v-btn v-btn--text theme--dark v-size--default" control-id="ControlID-11"><span class="v-btn__content"><div class="row text-button footer-button--text no-gutters align-center"><span class="material-symbols-outlined">  </span> <span class="ml-2">公告</span></div></span></button> <button type="button" class="small v-btn v-btn--text theme--dark v-size--default" control-id="ControlID-12"><span class="v-btn__content"><div class="row text-button footer-button--text no-gutters align-center"><span class="material-symbols-outlined"> </span> <span class="ml-2">下載</span></div></span></button> <button type="button" class="small v-btn v-btn--text theme--dark v-size--default" control-id="ControlID-13"><span class="v-btn__content"><div class="row text-button footer-button--text no-gutters align-center"> <span class="ml-2">建立捷徑</span></div></span></button></div> <div class="row pt-4 no-gutters justify-space-between"><div class="custom-text-noto text-body-2 col-md-6 col-12"><div class="row white--text pr-5 no-gutters"><div class="col col-12"><div class="v-image v-responsive mb-3 theme--dark" style="height:20px;max-width:178px;"><div class="v-responsive__sizer" style="padding-bottom: 12.2222%;"></div><div class="v-image__image v-image__image--cover" style="background-image: url(&quot;https://h5.xin-stars.com/_nuxt/img/waninlogo.89ad4a7.svg&quot;); background-position: center center;"></div><div class="v-responsive__content" style="width: 180px;"></div></div></div> <div class="col col-12"><p class="mb-0">
                網銀國際 Copyright©2013 WANIN INTERNATIONAL ALL Rights Reserved<br>
                服務專線：(04)2708-5191 週一至週日24HR<br>
                客服傳真：(04)2259-3887 <br>
                服務信箱：service@cs.wanin.tw
              </p></div></div></div> <div class="white--text custom-text-noto text-body-2 pt-xl-0 pt-lg-0 pt-md-0 pt-sm-4 pt-4 col-md-6 col-12"><div class="row flex-nowrap no-gutters"><div style="width:48px;"><div class="v-image v-responsive theme--dark" style="height:48px;width:48px;"><div class="v-responsive__sizer" style="padding-bottom: 100%;"></div><div class="v-image__image v-image__image--cover" style="background-image: url(&quot;https://img.xinverse.xyz/base_image/ab08031e//icon/18plus.svg&quot;); background-position: center center;"></div><div class="v-responsive__content" style="width: 150px;"></div></div></div> <div><ul type="disc" class="ml-4 mb-0 white--text custom-text-noto text-body-2"><li>
                  提醒您，長時間連續進行遊戲可能沉迷影響身心健康。
                </li> <li>
                  內建遊戲商城，須另外支付遊戲點數方能使用，遊戲點數一經購入兌換遊戲幣後無法以任何理由退換現金。
                </li> <li>
                  本遊戲情節涉及棋牌益智及娛樂，非現金交易賭博，使用者請勿進行非法遊戲幣交易。
                </li> <li>
                  此為機會中獎商品，消費者購買或參與活動不代表即可獲得特定商品。
                </li> <li>
                  如發現遊戲館有侵權狀況，歡迎使用網站底下的連絡管道
                </li></ul></div></div></div> <div class="pt-4 col col-12"><hr role="separator" aria-orientation="horizontal" class="v-divider theme--dark"></div></div> <div class="row pt-4 pb-2 no-gutters align-center justify-space-between"><div class="custom-text-noto text-body-2 col-md-6 col-12"><div class="pr-5 v-card v-sheet theme--dark elevation-0 transparent"><button target="blank" type="button" class="no-shadow px-0 v-btn v-btn--text theme--dark elevation-0 v-size--default transparent--text" control-id="ControlID-14"><span class="v-btn__content"><span class="white--text">
                使用者條款
              </span> <span class="white--text px-1">
                |
              </span></span></button><button target="blank" type="button" class="no-shadow px-0 v-btn v-btn--text theme--dark elevation-0 v-size--default transparent--text" control-id="ControlID-15"><span class="v-btn__content"><span class="white--text">
                隱私權條款
              </span> <span class="white--text px-1">
                |
              </span></span></button><button target="blank" type="button" class="no-shadow px-0 v-btn v-btn--text theme--dark elevation-0 v-size--default transparent--text" control-id="ControlID-16"><span class="v-btn__content"><span class="white--text">
                遊戲管理規章
              </span> <span class="white--text px-1">
                |
              </span></span></button><button target="blank" type="button" class="no-shadow px-0 v-btn v-btn--text theme--dark elevation-0 v-size--default transparent--text" control-id="ControlID-17"><span class="v-btn__content"><span class="white--text">
                智慧財產權政策
              </span> <span class="white--text px-1" style="display:none;">
                |
              </span></span></button></div></div> <div class="pa-0 pt-xl-0 pt-lg-0 pt-md-0 pt-4 col-md-6 col-12"><div class="d-flex align-center justify-start v-card v-sheet theme--dark elevation-0 transparent"><!----> <div tabindex="0" class="cursor-pointer rouned-circle v-card v-card--link v-sheet theme--dark transparent ml-1 mr-2" style="height:24px;width:24px;"><div class="v-image v-responsive theme--dark" style="height:100%;width:100%;"><div class="v-responsive__sizer" style="padding-bottom: 100%;"></div><div class="v-image__image v-image__image--cover" style="background-image: url(&quot;https://img.xinverse.xyz/base_image/ab08031e//icon/facebook.svg&quot;); background-position: center center;"></div><div class="v-responsive__content" style="width: 24px;"></div></div> <!----></div><div tabindex="0" class="cursor-pointer rouned-circle v-card v-card--link v-sheet theme--dark transparent ml-1 mr-2" style="height:24px;width:24px;"><div class="v-image v-responsive theme--dark" style="height:100%;width:100%;"><div class="v-responsive__sizer" style="padding-bottom: 100%;"></div><div class="v-image__image v-image__image--cover" style="background-image: url(&quot;https://img.xinverse.xyz/base_image/ab08031e//icon/instagram.svg&quot;); background-position: center center;"></div><div class="v-responsive__content" style="width: 150px;"></div></div> <!----></div><div tabindex="0" class="cursor-pointer rouned-circle v-card v-card--link v-sheet theme--dark transparent ml-1 mr-2" style="height:24px;width:24px;"><div class="v-image v-responsive theme--dark" style="height:100%;width:100%;"><div class="v-responsive__sizer" style="padding-bottom: 100%;"></div><div class="v-image__image v-image__image--cover" style="background-image: url(&quot;https://img.xinverse.xyz/base_image/ab08031e//icon/youtube.svg&quot;); background-position: center center;"></div><div class="v-responsive__content" style="width: 48px;"></div></div> <!----></div> <div tabindex="0" class="ml-2 cursor-pointer rouned-circle v-card v-card--link v-sheet theme--dark transparent" style="height:26px;width:106px;"><div class="v-image v-responsive theme--dark" style="height:100%;width:100%;"><div class="v-responsive__sizer" style="padding-bottom: 24.6479%;"></div><div class="v-image__image v-image__image--cover" style="background-image: url(&quot;https://img.xinverse.xyz/base_image/ab08031e//icon/footer-logo.png&quot;); background-position: center center;"></div><div class="v-responsive__content" style="width: 142px;"></div></div></div></div></div></div></div></div>
    </v-footer>
</template>